### ISSUE TITLE
escaping untrusted text arguments

### ISSUE THREAD

**Issue by sberan** [zeekay/executive#11]
Say I have some untrusted text, is there a recommended way to escape the contents of the text as an argument?

```
  var exec = require('executive')
  var untrustedText = /* some text here */
  
  exec(`say '${untrustedText}'`)
```

In this example, I would assume that I have a shell injection vulnerability, since the `untrustedText` variable could have a single quote, i.e. `hello'; rm -rf /` which could hose my computer. Any idea how to fix this?

**Comment by zeekay** [comment]
That's a good question, kind of depends on what your expected input is, I'm not sure there is a great way to handle this outside of just ensuring your argument to `say` (in this case) is quoted correctly.

**Comment by zeekay** [comment]
Something like [shell-escape](https://www.npmjs.com/package/shell-escape) might work for your given example.

**Comment by sberan** [comment]
thanks @zeekay - shell-escape is working wonderfully. Would you be interested in a PR to incorporate shell-escape into executive?

**Comment by zeekay** [comment]
Yeah that might not be a bad idea.

**Comment by sberan** [comment]
k, I'll think about it
