### ISSUE TITLE
Forward process.env to subprocesses by default

### ISSUE THREAD

**Issue by scottmas** [zeekay/executive#39]
Node child_process.spawn provides a way to forward process.env to sub processes, but Executive is not using them. See https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options on the section describing the third argument.

However the following prints nothing:
```
const exec = require('executive')
process.env.NODE_ENV = 'test';
exec('echo $NODE_ENV').then(() => {
  console.log('done');
})
```

**Comment by zeekay** [comment]
Hm, odd. We do pass `env`, which inherits from `process.env` automatically.

**Comment by scottmas** [comment]
Hmmm... let me look into this a bit more. I looked a bit more and it does work if a new node script is invoked. Just not printing a shell script.

**Comment by scottmas** [comment]
I think it likely has something to do with the distinction between `export NODE_ENV=something` vs `NODE_ENV=something` in bash scripting. Basically, there must be something in node core that doesn't pass non exported changes to process.env to new bash commands. 

Anyhow, closing this since the behavior is not due to executive. Thanks for the quick response! I do love this little library.

**Comment by zeekay** [comment]
Thanks! This is something that does work correctly with `child_process.exec`, but executive is built on top of `child_process.spawn`. The downside of `exec/execSync` is that they buffer output and always spawn a shell (which is what you need in this case). I think as a simple fix I'm going to detect shell built-ins and automatically set `shell: true`.

**Comment by zeekay** [comment]
This should work with latest executive, 1.5.0.

**Comment by scottmas** [comment]
Cool, thanks!
