### ISSUE TITLE
Error in piping

### ISSUE THREAD

**Issue by Nic2012** [zeekay/executive#9]
I have sth like this
```
exec.quiet( 'cat version.txt | jq -s -R -f version.jq' )
```
I am getting an error as result ```cat: invalid option -- 'R'```
It seems that the output from cat isnt piping to the jq prog.

Whats wrong ?
Thanks for any support and best regards,
Nic

**Comment by zeekay** [comment]
Pipe isn't supported although that  would be nice.

**Comment by zeekay** [comment]
Now supported with 1.x.x.
